name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build-rust:
    name: "Rust Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, rust-src
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-python:
    name: "Python ${{ matrix.python-version }} Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install setuptools_rust flake8 yapf flake8-quotes
      - name: Check Python formatting
        run: |
          flake8 --inline-quotes="double" ./doc/
          flake8 --inline-quotes="double" ./python/
          yapf --diff --recursive ./doc/
          yapf --diff --recursive ./python/
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Build
        # Building with develop is faster than with install
        run: python python/setup.py develop
