name: Documentation
on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -D warnings
  rust_toolchain: nightly-2022-02-09

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install supported Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          profile: minimal
          override: true
          components: rust-docs
      - uses: Swatinem/rust-cache@v1
      - name: Build Documentation
        run: cargo doc --workspace --no-deps --all-features

  pythondoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Python dependencies
        run: python -m pip install -r python/doc/requirements-doc.txt
      - name: Build Documentation
        run: |
          cd python/doc
          make html SPHINXOPTS="-W --keep-going -n"
