name: Python Wheels
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-wheels:
    name: Build Python Wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Wheels in Docker
        uses: docker://quay.io/pypa/manylinux1_x86_64
        env:
          CARGO_TERM_COLOR: always
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: python-wheels
          path: dist
